// <auto-generated />
using System;
using ExamenRibbit.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenRibbit.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ExamenRibbit.Entities.Tables.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadEnStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadEnStock = 10,
                            FechaCreacion = new DateTime(2025, 1, 15, 4, 47, 57, 156, DateTimeKind.Utc).AddTicks(5506),
                            Nombre = "Refresco",
                            Precio = 100m
                        },
                        new
                        {
                            Id = 2,
                            CantidadEnStock = 20,
                            FechaCreacion = new DateTime(2025, 1, 15, 4, 47, 57, 156, DateTimeKind.Utc).AddTicks(5653),
                            Nombre = "Tortilla",
                            Precio = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
